# Generated by Django 3.2 on 2022-12-07 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0005_worker_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0022_auto_20221104_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee_data', models.CharField(max_length=50, verbose_name='Datos del consumidor')),
                ('destiny', models.TextField(verbose_name='Dirección de destino')),
                ('type_delivery', models.CharField(choices=[('Corto', 'Corto = 1.5'), ('Corto + acompañante', 'Corto + acompañante = 2.0'), ('Largo', 'Largo = 2.5'), ('Largo + acompañante', 'Largo + acompañante = 3.0'), ('Extra largo', 'Extra largo = 3.5'), ('Extra largo + acompañante', 'Extra largo + acompañante = 4.0'), ('Carro corto', 'Carro corto = 2.0'), ('Carro largo', 'Carro largo = 3.0'), ('Carro Extra largo', 'Carro Extra largo= 4.0'), ('Preferencial', 'Preferencial')], max_length=30, verbose_name='Tipo de delivery')),
                ('type_delivery_amount', models.FloatField(max_length=3, verbose_name='Tipo de delivery')),
                ('preferred_price', models.FloatField(blank=True, max_length=3, null=True, verbose_name='Precio preferencial')),
                ('type_service', models.CharField(choices=[('Delivery', 'Delivery'), ('Transporte', 'Transporte')], default='Delivery', max_length=12, verbose_name='Tipo de servicio')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('status_delivery', models.BooleanField(verbose_name='¿Ha sido pagado el servicio?')),
                ('recieved_money', models.FloatField(default=0, verbose_name='Dinero recibido')),
                ('status_recieved_money', models.BooleanField(verbose_name='¿Ha sido entregado al cliente el dinero recibido?')),
                ('serial', models.CharField(default='9¬5G}RQ2FD$/W17a&S3u~#eZEjcOfUp{0dA]wCbhogv[?Y8X·qP!%tIMsiLz', max_length=70)),
                ('centralist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Centralista')),
                ('distributing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Repartidor')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliverys',
            },
        ),
    ]
