# Generated by Django 3.2 on 2022-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='serial',
            field=models.CharField(default='·Gtz/2r½8?a(sB{nce!K$}fUO1vmuMiAyº9k@=S~ZRXlL0&CPW#6g[Qw]73%', max_length=70),
        ),
    ]
