# Generated by Django 3.2 on 2022-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='serial',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
