# Generated by Django 3.2 on 2022-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLocal', models.CharField(max_length=50, verbose_name='Local')),
                ('debit', models.FloatField(verbose_name='Deuda')),
                ('localPhone', models.CharField(max_length=11, verbose_name='número')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
