# Generated by Django 3.2 on 2022-10-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_localphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='localPhone',
            new_name='local_phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nameLocal',
            new_name='name_local',
        ),
    ]
