# Generated by Django 3.2 on 2022-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20221008_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='debit',
            field=models.FloatField(default=0, verbose_name='Deuda'),
        ),
    ]
