# Generated by Django 3.2 on 2022-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addressee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_addressee', models.CharField(max_length=50, verbose_name='Datos del destinatario')),
                ('destiny', models.TextField(verbose_name='Dirección de destino')),
            ],
            options={
                'verbose_name': 'Addressee',
                'verbose_name_plural': 'Addressees',
            },
        ),
    ]
