# Generated by Django 3.2 on 2022-10-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_addressee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Destinatario de'),
            preserve_default=False,
        ),
    ]
