# Generated by Django 3.2 on 2022-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_addressee_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='google_map',
            field=models.URLField(default='www.alsdf.com', verbose_name='Direccion de google map'),
            preserve_default=False,
        ),
    ]
