# Generated by Django 3.2 on 2022-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_addressee_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='direction',
            field=models.TextField(default=1, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressee',
            name='destiny',
            field=models.TextField(verbose_name='Dirección'),
        ),
    ]
