# Generated by Django 3.2 on 2022-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20221015_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='photo',
            field=models.ImageField(default='w', upload_to='', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
