# Generated by Django 3.2 on 2022-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_addressee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_addressee', verbose_name='Foto'),
        ),
    ]
