# Generated by Django 3.2 on 2022-11-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_auto_20221023_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='data_addressee',
            field=models.CharField(max_length=50, verbose_name='Datos del consumidor'),
        ),
        migrations.AlterField(
            model_name='addressee',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente'),
        ),
    ]
