# Generated by Django 3.2 on 2022-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=16, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'workers',
            },
        ),
    ]
