# Generated by Django 3.2 on 2022-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
