# Generated by Django 3.2 on 2022-10-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
