# Generated by Django 3.2 on 2022-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
